stages:
  - build
  - push
  - deploy

variables:
  IMAGE_TAG: "latest"
  IMAGE_NAME: "gcr.io/genuine-park-463208-g0/nginx-demo"

build:
  stage: build
  script:
    - echo "🔧 Building Docker image..."
    - docker build -t $IMAGE_NAME:$IMAGE_TAG ./nginx
  only:
    - main

push:
  stage: push
  script:
    - echo "📦 Pushing Docker image to GCR..."
    - echo "$GCP_SA_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud auth configure-docker
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "🚀 Deploying to GKE using Helm..."
    - echo "$GCP_SA_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project genuine-park-463208-g0
    - gcloud config set compute/zone us-central1-a
    - gcloud container clusters get-credentials payfuture-gke-cluster
    - helm upgrade --install nginx ./helm/nginx --namespace dev --create-namespace
  only:
    - main
