name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: genuine-park-463208-g0
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials payfuture-gke-cluster \
            --zone us-central1-a \
            --project genuine-park-463208-g0

      - name: Deploy with Helm
        run: |
          helm upgrade --install nginx ./helm/nginx \
            --namespace dev \
            --create-namespace
