name: Deploy to GKE using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: genuine-park-463208-g0
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials payfuture-gke-cluster --zone us-central1-a --project genuine-park-463208-g0

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Deploy NGINX using Helm
      run: |
        helm upgrade --install nginx-release ./helm/nginx --namespace dev --create-namespace
